export const menModel = [
  {
    id: "men1",
    category: "men",
    brand: "UZee",
    imgURL: "https://rukminim1.flixcart.com/image/580/696/k2krekw0/t-shirt/h/f/8/m-triple-navy-mhrn-panel-uzee-original-imafhwjzayxpdbmb.jpeg?q=50",
    description: "Color Block Men Round Neck White, Maroon T-Shirt",
    price: 600,
  },
  {
    id: "men2",
    category: "men",
    brand: "Aelomart",
    imgURL: "https://rukminim1.flixcart.com/image/580/696/kfoapow0-0/t-shirt/z/h/l/l-am-1021m-aelomart-original-imafw2jwmdmz3ayz.jpeg?q=50",
    description: "Color Block Men Round Neck White, Maroon T-Shirt",
    price: 620,
  },
  {
    id: "men3",
    category: "men",
    brand: "Eyebogler",
    imgURL: "https://rukminim1.flixcart.com/image/580/696/kkfrjww0/t-shirt/h/1/t/l-t312-cgblwh-new-eyebogler-original-imafzs5hrjgzsfpr.jpeg?q=50",
    description: "Color Block Men Round Neck White, Maroon T-Shirt",
    price: 900,
  },
  {
    id: "men4",
    category: "men",
    brand: "Seven Rocks",
    imgURL: "https://rukminim1.flixcart.com/image/580/696/khmbafk0-0/t-shirt/w/j/s/xs-t322-blwh-seven-rocks-original-imafxhagtyj2xvpn.jpeg?q=50",
    description: "Color Block Men Round Neck White, Maroon T-Shirt",
    price: 499,
  },
  {
    id: "men5",
    category: "men",
    brand: "HELMONT",
    imgURL: "https://rukminim1.flixcart.com/image/310/372/kf75fgw0-0/t-shirt/f/6/j/xxl-t325-pwgh-seven-rocks-original-imafvpbgf6nchmfj.jpeg?q=50",
    description: "Color Block Men Round Neck White, Maroon T-Shirt",
    price: 799,
  },
  {
    id: "men6",
    category: "men",
    brand: "TRIPR",
    imgURL: "https://rukminim1.flixcart.com/image/580/696/kvpklu80/t-shirt/b/j/e/m-12011186-fila-original-imag8juxwh6axysf.jpeg?q=50",
    description: "Color Block Men Round Neck White, Maroon T-Shirt",
    price: 499,
  },
  {
    id: "men7",
    category: "men",
    brand: "FILA",
    imgURL:
      "https://rukminim1.flixcart.com/image/580/696/kjkbv680-0/t-shirt/9/v/o/m-t285hs-as7whdngr-seven-rocks-original-imafz3wkfs8pevqc.jpeg?q=50",
    description: "Color Block Men Round Neck White, Maroon T-Shirt",
    price: 299,
  },
  {
    id: "men8",
    category: "men",
    brand: "Seven Rocks",
    imgURL: "https://rukminim1.flixcart.com/image/310/372/khdqnbk0/t-shirt/r/u/0/m-fc4173-fastcolors-original-imafxettxhthw8ye.jpeg?q=50",
    description: "Color Block Men Round Neck White, Maroon T-Shirt",
    price: 799,
  },
  {
    id: "men9",
    category: "men",
    brand: "UZee",
    imgURL: "https://rukminim1.flixcart.com/image/580/696/kf1fo280hlty2aw-0/t-shirt/w/s/e/-original-imafdfvvr8hqdu65.jpeg?q=50",
    description: "Color Block Men Round Neck White, Maroon T-Shirt",
    price: 399,
  },
  {
    id: "men10",
    category: "men",
    brand: "FLEXIMAA",
    imgURL: "https://rukminim1.flixcart.com/image/310/372/kl2mljk0/t-shirt/a/3/k/4xl-tblhdfulmask-lion-tripr-original-imagy9tcx7q25wym.jpeg?q=50",
    description: "Color Block Men Round Neck White, Maroon T-Shirt",
    price: 299,
  },
];

export const womenModel = [
  {
    id: "women1",
    category: "women",
    brand: "FLEXIMAA",
    imgURL: "https://rukminim1.flixcart.com/image/339/407/khxqt8w0/top/9/t/h/m-wltpsogreymilange-m-fleximaa-original-imafxuehhc2vx9yz.jpeg?q=50",
    description: "Casual Regular Sleeves Printed Women Grey Top",
    price: 810,
  },
  {
    id: "women2",
    category: "women",
    brand: "LEVI'S",
    imgURL: "https://rukminim1.flixcart.com/image/339/407/ktd9mkw0/t-shirt/o/w/q/s-23771-0246-levi-s-original-imag6qbxknvs7bqh.jpeg?q=50",
    description: "Printed Women Round Neck White T-Shirt",
    price: 600,
  },
  {
    id: "women3",
    category: "women",
    brand: "GIRLS SHOPPIE",
    imgURL: "https://rukminim1.flixcart.com/image/339/407/ksc46fk0/t-shirt/t/y/p/xs-wmb-girls-shoppie-original-imag5xe3sdhgg8sg.jpeg?q=50",
    description: "Color Block Men Round Neck Black, Maroon T-Shirt",
    price: 560,
  },
  {
    id: "women4",
    category: "women",
    brand: "FLEXIMAA",
    imgURL: "https://rukminim1.flixcart.com/image/339/407/k23m4cw0/top/r/k/q/s-tttp003130-tokyo-talkies-original-imafhgvqkgap2dtb.jpeg?q=50",
    description: "Casual Regular Sleeves Printed Women Grey Top",
    price: 800,
  },
  {
    id: "women5",
    category: "women",
    brand: "Tokyo Talkies",
    imgURL: "https://rukminim1.flixcart.com/image/339/407/khxqt8w0/top/9/t/h/m-wltpsogreymilange-m-fleximaa-original-imafxuehhc2vx9yz.jpeg?q=50",
    description: "Casual Regular Sleeves Solid Women Maroon Top",
    price: 800,
  },
  {
    id: "women6",
    category: "women",
    brand: "GIRLS SHOPPIE",
    imgURL: "https://rukminim1.flixcart.com/image/339/407/kltryq80/t-shirt/u/6/p/xl-wkb-girls-shoppie-original-imagyvfxdaharypp.jpeg?q=50",
    description: "Striped Women Round Neck Blue, White T-Shirt",
    price: 678,
  },
  {
    id: "women7",
    category: "women",
    brand: "Selvia",
    imgURL: "https://rukminim1.flixcart.com/image/339/407/km0x5zk0/top/j/z/o/m-178tkr2901-selvia-original-imagfyqfytkkfpkn.jpeg?q=50",
    description: "Casual Regular Sleeves Solid Women Maroon Top",
    price: 345,
  },
  {
    id: "women8",
    category: "women",
    brand: "Tokyo Talkies ",
    imgURL: "https://rukminim1.flixcart.com/image/880/1056/k0flmkw0/top/7/u/n/l-tttp003124-tokyo-talkies-original-imafk8ynguyznyvv.jpeg?q=50",
    description: "Casual Regular Sleeves Printed Women Yellow Top",
    price: 380,
  },
  {
    id: "women9",
    category: "women",
    brand: "Dressberry ",
    imgURL: "https://rukminim1.flixcart.com/image/880/1056/k12go7k0/shirt/y/f/5/s-8883945-dressberry-original-imafkphcdsmwjsxa.jpeg?q=50",
    description: "Women Regular Fit Printed Spread Collar Casual Shirt",
    price: 640,
  },
  {
    id: "women10",
    category: "women",
    brand: "indibelle ",
    imgURL: "https://rukminim1.flixcart.com/image/880/1056/jpodaq80/shrug/n/e/q/3xl-ibcp255ml-indibelle-original-imafbufrktnbhwg8.jpeg?q=50",
    description: "Women Straight Half Sleeve Multicolor Shrug",
    price: 500,
  },
];

export const electronicsModel = [
  {
    id: "electronics1",
    category: "electronics",
    brand: "realme ",
    imgURL: "https://rukminim1.flixcart.com/image/416/416/kvzkosw0/headphone/i/i/o/-original-imag8rdvk9nebjkg.jpeg?q=70",
    description: "DIZO by realme TechLife GoPods D with Enviornment Noise Cancellation (ENC) Bluetooth Headset ",
    price: 1299,
  },
  {
    id: "electronics2",
    category: "electronics",
    brand: "realme ",
    imgURL: "https://rukminim1.flixcart.com/image/416/416/kvzkosw0/headphone/j/c/n/-original-imag8rdvyeryzgrc.jpeg?q=70",
    description: "DIZO by realme TechLife GoPods D with Enviornment Noise Cancellation (ENC) Bluetooth Headset",
    price: 500,
  },
  {
    id: "electronics3",
    category: "electronics",
    brand: "boAt ",
    imgURL:
      "https://rukminim1.flixcart.com/image/416/416/ksdjma80/headphone/o/f/c/airdopes-131-airdopes-138-boat-original-imag5yz96jehyqrg.jpeg?q=70",
    description: "boAt Airdopes 131 Bluetooth Headset",
    price: 1199,
  },
  {
    id: "electronics4",
    category: "electronics",
    brand: "OnePlus ",
    imgURL: "https://rukminim1.flixcart.com/image/416/416/kg8avm80-0/headphone/2/p/r/e304a-oneplus-original-imafwgkvchwhf63s.jpeg?q=70",
    description: "OnePlus Bullets Wireless Z Bass Edition Bluetooth Headset  (Reverb Red, In the Ear)",
    price: 1999,
  },
  {
    id: "electronics5",
    category: "electronics",
    brand: "JBL",
    imgURL: "https://rukminim1.flixcart.com/image/416/416/juwzf680/headphone-refurbished/7/h/k/z-c100si-jbl-original-imaffxja5vmgwudz.jpeg?q=70",
    description: "JBL C150SI Wired Headset  (Black, In the Ear)",
    price: 699,
  },
  {
    id: "electronics6",
    category: "electronics",
    brand: "realme ",
    imgURL: "https://rukminim1.flixcart.com/image/416/416/krayqa80/headphone/v/k/q/rma2009-realme-original-imag54f5hsazzk99.jpeg?q=70",
    description: "realme Buds Wireless 2 with Dart Charge and Active Noise Cancellation (ANC) Bluetooth Headset  (Grey, In the Ear)",
    price: 2299,
  },
  {
    id: "electronics7",
    category: "electronics",
    brand: "Truke ",
    imgURL: "https://rukminim1.flixcart.com/image/416/416/kmwcuq80/headphone/h/d/k/e21-truke-original-imagfp8fbsz6qbgx.jpeg?q=70",
    description: "Truke Buds Q1 with Environmental Noise Cancellation(ENC) Bluetooth Headset  (Black, True Wireless)",
    price: 500,
  },
  {
    id: "electronics8",
    category: "electronics",
    brand: "boAt ",
    imgURL:
      "https://rukminim1.flixcart.com/image/416/416/ksdjma80/headphone/u/4/o/airdopes-131-airdopes-138-boat-original-imag5yzacvxdzu6p.jpeg?q=70",
    description: "boAt Airdopes 131 Bluetooth Headset  (Cherry Blossom, True Wireless)",
    price: 1199,
  },
  {
    id: "electronics9",
    category: "electronics",
    brand: "realme ",
    imgURL: "https://rukminim1.flixcart.com/image/416/416/krntoy80/headphone/5/2/o/ydjc02wm-redmi-original-imag5eg9pbxp8rvf.jpeg?q=70",
    description: "Redmi by Mi Hi-Resolution Audio Wired Headset  (Black, In the Ear)",
    price: 599,
  },
  {
    id: "electronics10",
    category: "electronics",
    brand: "boAt ",
    imgURL:
      "https://rukminim1.flixcart.com/image/416/416/kingqkw0-0/speaker/mobile-tablet-speaker/s/8/i/stone-350-boat-original-imafyebfuaumdezs.jpeg?q=70",
    description: "boAt Stone 350 10 W Bluetooth Speaker  (Black, Mono Channel)",
    price: 1499,
  },
];

export const bookmarks = [];
